version: '3.8'

services:
  # The Database
  db:
    image: postgres:15
    container_name: factory_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=predictive_maintenance
    ports:
      - "5433:5432" # Using 5433 externally to avoid conflict with native PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data # Save data even if container stops

volumes:
  postgres_data:
